# -*- coding: utf-8 -*-
"""soall.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDz5qWnaUqnNX4g0ef_QtO4e16pemmB1
"""

def identifikasi_hama(daun_menguning, bercak_hitam, daun_berlubang, tanaman_layu):
    hasil = []

    if daun_menguning and tanaman_layu:
        hasil.append("Hama Wereng")
    if bercak_hitam:
        hasil.append("Hama Jamur")
    if daun_berlubang:
        hasil.append("Hama Ulat")
    if tanaman_layu and not bercak_hitam:
        hasil.append("Hama Akar")

    if not hasil:
        hasil.append("Hama tidak diketahui")

    return hasil

# Contoh input
G1 = bool(int(input("Apakah daun menguning? (1 = ya, 0 = tidak): ")))
G2 = bool(int(input("Apakah ada bercak hitam? (1 = ya, 0 = tidak): ")))
G3 = bool(int(input("Apakah daun berlubang? (1 = ya, 0 = tidak): ")))
G4 = bool(int(input("Apakah tanaman layu? (1 = ya, 0 = tidak): ")))

hasil = identifikasi_hama(G1, G2, G3, G4)

print("Jenis Hama yang terdeteksi:")
for hama in hasil:
    print("-", hama)